DROP VIEW IF EXISTS TOP5_CATEGORIERENTABLE;

DROP VIEW IF EXISTS TOP5_CATEGORIERENTABLETMP;

DROP VIEW IF EXISTS COMMISSIONCATEGORIE;

DROP VIEW IF EXISTS CATEGORIEPRODUIT;

DROP VIEW IF EXISTS TOP5_CATEGORIEPRODUIT;

DROP VIEW IF EXISTS CAM_PARAN;

DROP VIEW IF EXISTS CA_PARAN;

DROP VIEW IF EXISTS CAM_PARMOIS;

DROP VIEW IF EXISTS CA_PARMOIS;

DROP VIEW IF EXISTS CAM_PARJOUR;

DROP VIEW IF EXISTS CA_PARJOUR;

DROP TABLE IF EXISTS ADMIN;

DROP TABLE IF EXISTS DEMANDE;

DROP TABLE IF EXISTS CHIFFREAFFAIRE;

DROP TABLE IF EXISTS COMMISSION;

DROP TABLE IF EXISTS HISTORIQUEUTILISATEUR;

DROP TABLE IF EXISTS PRODUIT;

DROP TABLE IF EXISTS CATEGORIE;

DROP TABLE IF EXISTS UTILISATEUR;

CREATE TABLE ADMIN(
    ID SERIAL PRIMARY KEY,
    PSEUDO VARCHAR(50),
    MOTDEPASSE VARCHAR(50)
);

CREATE TABLE UTILISATEUR(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    MAIL VARCHAR(150),
    MOTDEPASSE VARCHAR(50),
    SOLDE FLOAT DEFAULT 0
);

CREATE TABLE DEMANDE(
    ID SERIAL PRIMARY KEY,
    IDUTILISATEUR INT4 REFERENCES UTILISATEUR(ID),
    MONTANT FLOAT,
    ETAT INT4 DEFAULT 0,
    DATEDEMANDE TIMESTAMP
);

CREATE TABLE CATEGORIE(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR(50),
    DUREEMAX TIME,
    ETAT INT4 DEFAULT 0
);

CREATE TABLE PRODUIT(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR(100),
    PRIX FLOAT,
    UTILISATEURID INT4 REFERENCES UTILISATEUR(ID),
    CATEGORIEID INT4 REFERENCES CATEGORIE(ID),
    DATEENCHERISER TIMESTAMP,
    DUREE TIME
);

CREATE TABLE HISTORIQUEUTILISATEUR(
    ID SERIAL PRIMARY KEY,
    NOM VARCHAR(100),
    PRIX FLOAT,
    UTILISATEURID INT4 REFERENCES UTILISATEUR(ID),
    CATEGORIEID INT4 REFERENCES CATEGORIE(ID),
    DATEENCHERISER TIMESTAMP,
    DUREE TIME
);

CREATE TABLE CHIFFREAFFAIRE(
    ID SERIAL PRIMARY KEY,
    PRIX FLOAT,
    DATEAFFAIRE TIMESTAMP,
    PRODUITID INT4 REFERENCES PRODUIT(ID)
);

CREATE TABLE COMMISSION(
    ID SERIAL PRIMARY KEY,
    PRIX FLOAT,
    DATECOMMISSION DATE,
    IDPRODUIT INT4 REFERENCES PRODUIT(ID)
);

-- TOP 5 DES CATEGORIES ***
CREATE OR REPLACE VIEW TOP5_CATEGORIEPRODUIT AS
    SELECT
        C.ID,
        C.NOM,
        COUNT(*) NBR
    FROM
        CATEGORIE C
        JOIN PRODUIT P
        ON C.ID = P.CATEGORIEID
    GROUP BY
        C.ID
    ORDER BY
        NBR DESC LIMIT 5;

-- TOP 5 DES CATEGORIE RENTABLE
CREATE OR REPLACE VIEW CATEGORIEPRODUIT AS
    SELECT
        C.ID,
        C.NOM,
        P.ID AS IDPRODUIT
    FROM
        CATEGORIE C
        JOIN PRODUIT P
        ON C.ID = P.CATEGORIEID;

CREATE OR REPLACE VIEW COMMISSIONCATEGORIE AS
    SELECT
        CATEGORIEPRODUIT.*,
        COMMISSION.PRIX
    FROM
        COMMISSION
        JOIN CATEGORIEPRODUIT
        ON COMMISSION.IDPRODUIT = CATEGORIEPRODUIT.IDPRODUIT;

CREATE OR REPLACE VIEW TOP5_CATEGORIERENTABLETMP AS
    SELECT
        ID,
        SUM(PRIX) TOTAL
    FROM
        COMMISSIONCATEGORIE
    GROUP BY
        ID
    ORDER BY
        TOTAL DESC LIMIT 5;

-- ***
CREATE OR REPLACE VIEW TOP5_CATEGORIERENTABLE AS
    SELECT
        TOP5_CATEGORIERENTABLETMP.ID,
        TOP5_CATEGORIERENTABLETMP.TOTAL,
        CATEGORIE.NOM
    FROM
        TOP5_CATEGORIERENTABLETMP
        JOIN CATEGORIE
        ON TOP5_CATEGORIERENTABLETMP.ID = CATEGORIE.ID;

-- CHIFFRE D'AFFAIRE
-- MOYENNE PAR JOUR

-- CHIFFRE D'AFFAIRE PAR JOUR
CREATE OR REPLACE VIEW CA_PARJOUR AS
    SELECT
        SUM(PRIX) AS PRIX
    FROM
        COMMISSION
    GROUP BY
        DATECOMMISSION;

-- CHIFFRE D'AFFAIRE MOYENNE PAR JOUR ***
CREATE OR REPLACE VIEW CAM_PARJOUR AS
    SELECT
        (SUM(PRIX) / COUNT(*)) MOYENNE
    FROM
        CA_PARJOUR;

-- CHIFFRE D'AFFAIRE PAR MOIS
CREATE OR REPLACE VIEW CA_PARMOIS AS
    SELECT
        PRIX,
        EXTRACT(MONTH
    FROM
        DATECOMMISSION)
    FROM
        COMMISSION;

-- CHIFFRE D'AFFAIRE MOYENNE PAR MOIS ****
CREATE OR REPLACE VIEW CAM_PARMOIS AS
    SELECT
        (SUM(PRIX) / COUNT(*)) AS MOYENNE
    FROM
        CA_PARMOIS;

-- CHIFFRE D'AFFAIRE PAR AN
CREATE OR REPLACE VIEW CA_PARAN AS
    SELECT
        PRIX,
        EXTRACT(YEAR
    FROM
        DATECOMMISSION)
    FROM
        COMMISSION;

-- CHIFFRE D'AFFAIRE MOYENNE PAR AN ***
CREATE OR REPLACE VIEW CAM_PARAN AS
    SELECT
        (SUM(PRIX) / COUNT(*)) AS MOYENNE
    FROM
        CA_PARMOIS;

--HISTORIQUE UTILISATEUR
SELECT
    H.ID,
    H.NOM,
    H.PRIX,
    H.DATEENCHERISER,
    H.DUREE,
    C.NOM AS CATEGORIE
FROM
    HISTORIQUEUTILISATEUR H
    JOIN CATEGORIE C
    ON C.ID = H.CATEGORIEID
WHERE
    UTILISATEURID=?;